
/**
 *
 * @author Shahd
 */
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
public class restaurantManagementSytsem extends javax.swing.JFrame {
 
    // create global variables to use it in and place
    
    int chickenNum ,meatNum ,frenchFreisNum,waterNum,pepsiNum;
    double chickenPrice,meatPrice ,frenchFreisPrice,waterPrice,pepsiPrice;
    final double CHICKEN_COST=50 , MEAT_COST=60 , FRENCH_FREIS_COST=25 , WATER_COST=8 , PEPSI_COST=15;
    double subTotal,tax,total;
    int billCounter;
    PrintWriter output;
    
    
    public restaurantManagementSytsem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        restaurantPanel = new javax.swing.JPanel();
        restaurantLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        billNum = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        sandwichesPanel = new javax.swing.JPanel();
        meatSandwichPrice = new javax.swing.JLabel();
        BeefShawarma = new javax.swing.JLabel();
        FrenchFries = new javax.swing.JLabel();
        chickenCounter = new javax.swing.JSpinner();
        meatCounter = new javax.swing.JSpinner();
        frenchFreisCounter = new javax.swing.JSpinner();
        sandwichesLabel = new javax.swing.JLabel();
        chickenextraCheese = new javax.swing.JCheckBox();
        meetExtraCheese = new javax.swing.JCheckBox();
        freisExtraCheese = new javax.swing.JCheckBox();
        chickenShawarma1 = new javax.swing.JLabel();
        frenchFreisSandwichPrice = new javax.swing.JLabel();
        checkenSndwichPrice = new javax.swing.JLabel();
        drinksPanel = new javax.swing.JPanel();
        drinksLabel = new javax.swing.JLabel();
        water = new javax.swing.JLabel();
        waterCounter = new javax.swing.JSpinner();
        waterprice = new javax.swing.JLabel();
        pepsi = new javax.swing.JLabel();
        pepsiCounter = new javax.swing.JSpinner();
        pepsiprice = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        price1 = new javax.swing.JPanel();
        price = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        subtotal = new javax.swing.JLabel();
        taxlabel = new javax.swing.JLabel();
        receiptPanel = new javax.swing.JPanel();
        Price2 = new javax.swing.JLabel();
        newreceipt = new javax.swing.JButton();
        saveReciept = new javax.swing.JButton();
        calculate2 = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        restaurantPanel.setBackground(new java.awt.Color(255, 255, 255));

        restaurantLabel.setBackground(new java.awt.Color(255, 255, 255));
        restaurantLabel.setFont(new java.awt.Font("Lucida Bright", 3, 48)); // NOI18N
        restaurantLabel.setForeground(new java.awt.Color(0, 102, 204));
        restaurantLabel.setText("SHMSH   RESTAURNAT ");

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 102, 204));
        exitButton.setText("Exit");
        exitButton.setToolTipText("");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        billNum.setBackground(new java.awt.Color(255, 255, 255));
        billNum.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 24)); // NOI18N
        billNum.setForeground(new java.awt.Color(0, 102, 204));
        billNum.setText("Bill number : 0");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shmsh.png"))); // NOI18N

        javax.swing.GroupLayout restaurantPanelLayout = new javax.swing.GroupLayout(restaurantPanel);
        restaurantPanel.setLayout(restaurantPanelLayout);
        restaurantPanelLayout.setHorizontalGroup(
            restaurantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restaurantPanelLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(restaurantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(restaurantPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(billNum, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(restaurantPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(restaurantLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        restaurantPanelLayout.setVerticalGroup(
            restaurantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restaurantPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(restaurantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaurantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(billNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(restaurantPanelLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sandwichesPanel.setBackground(new java.awt.Color(255, 255, 255));

        meatSandwichPrice.setBackground(new java.awt.Color(255, 255, 255));
        meatSandwichPrice.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 27)); // NOI18N
        meatSandwichPrice.setForeground(new java.awt.Color(0, 102, 204));
        meatSandwichPrice.setText("0.0 LE ");

        BeefShawarma.setBackground(new java.awt.Color(255, 255, 255));
        BeefShawarma.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 30)); // NOI18N
        BeefShawarma.setForeground(new java.awt.Color(0, 102, 204));
        BeefShawarma.setText("meat shawarma");

        FrenchFries.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 30)); // NOI18N
        FrenchFries.setForeground(new java.awt.Color(0, 102, 204));
        FrenchFries.setText("French Fries");

        chickenCounter.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        chickenCounter.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        chickenCounter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chickenCounterStateChanged(evt);
            }
        });

        meatCounter.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        meatCounter.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        meatCounter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                meatCounterStateChanged(evt);
            }
        });

        frenchFreisCounter.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        frenchFreisCounter.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        frenchFreisCounter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                frenchFreisCounterStateChanged(evt);
            }
        });

        sandwichesLabel.setBackground(new java.awt.Color(255, 255, 255));
        sandwichesLabel.setFont(new java.awt.Font("Palatino Linotype", 3, 48)); // NOI18N
        sandwichesLabel.setForeground(new java.awt.Color(0, 102, 204));
        sandwichesLabel.setText("Sandwiches");

        chickenextraCheese.setBackground(new java.awt.Color(255, 255, 255));
        chickenextraCheese.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        chickenextraCheese.setForeground(new java.awt.Color(0, 51, 153));
        chickenextraCheese.setText("Extra Cheese");
        chickenextraCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenextraCheeseActionPerformed(evt);
            }
        });

        meetExtraCheese.setBackground(new java.awt.Color(255, 255, 255));
        meetExtraCheese.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        meetExtraCheese.setForeground(new java.awt.Color(0, 51, 153));
        meetExtraCheese.setText("Extra Cheese");
        meetExtraCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetExtraCheeseActionPerformed(evt);
            }
        });

        freisExtraCheese.setBackground(new java.awt.Color(255, 255, 255));
        freisExtraCheese.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        freisExtraCheese.setForeground(new java.awt.Color(0, 51, 153));
        freisExtraCheese.setText("Extra Cheese");
        freisExtraCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freisExtraCheeseActionPerformed(evt);
            }
        });

        chickenShawarma1.setBackground(new java.awt.Color(255, 255, 255));
        chickenShawarma1.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 27)); // NOI18N
        chickenShawarma1.setForeground(new java.awt.Color(0, 102, 204));
        chickenShawarma1.setText("Chicken shawarma");

        frenchFreisSandwichPrice.setBackground(new java.awt.Color(255, 255, 255));
        frenchFreisSandwichPrice.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 27)); // NOI18N
        frenchFreisSandwichPrice.setForeground(new java.awt.Color(0, 102, 204));
        frenchFreisSandwichPrice.setText("0.0 LE ");

        checkenSndwichPrice.setBackground(new java.awt.Color(255, 255, 255));
        checkenSndwichPrice.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 27)); // NOI18N
        checkenSndwichPrice.setForeground(new java.awt.Color(0, 102, 204));
        checkenSndwichPrice.setText("0.0 LE ");

        javax.swing.GroupLayout sandwichesPanelLayout = new javax.swing.GroupLayout(sandwichesPanel);
        sandwichesPanel.setLayout(sandwichesPanelLayout);
        sandwichesPanelLayout.setHorizontalGroup(
            sandwichesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sandwichesPanelLayout.createSequentialGroup()
                .addGroup(sandwichesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sandwichesPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(sandwichesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sandwichesPanelLayout.createSequentialGroup()
                                .addComponent(FrenchFries, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(frenchFreisCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sandwichesPanelLayout.createSequentialGroup()
                                .addComponent(BeefShawarma, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(meatCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sandwichesPanelLayout.createSequentialGroup()
                                .addComponent(chickenShawarma1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chickenCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(sandwichesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(meetExtraCheese)
                            .addComponent(chickenextraCheese)
                            .addComponent(freisExtraCheese))
                        .addGap(87, 87, 87)
                        .addGroup(sandwichesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkenSndwichPrice)
                            .addComponent(frenchFreisSandwichPrice)
                            .addComponent(meatSandwichPrice)))
                    .addGroup(sandwichesPanelLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(sandwichesLabel)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        sandwichesPanelLayout.setVerticalGroup(
            sandwichesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sandwichesPanelLayout.createSequentialGroup()
                .addComponent(sandwichesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(sandwichesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chickenShawarma1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chickenCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chickenextraCheese)
                    .addComponent(checkenSndwichPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(sandwichesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sandwichesPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(sandwichesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(meatCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meetExtraCheese)
                            .addComponent(BeefShawarma, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(sandwichesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FrenchFries, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frenchFreisCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(freisExtraCheese))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(sandwichesPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(meatSandwichPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(frenchFreisSandwichPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(70, Short.MAX_VALUE))))
        );

        drinksPanel.setBackground(new java.awt.Color(255, 255, 255));

        drinksLabel.setBackground(new java.awt.Color(255, 255, 255));
        drinksLabel.setFont(new java.awt.Font("Palatino Linotype", 3, 50)); // NOI18N
        drinksLabel.setForeground(new java.awt.Color(0, 102, 204));
        drinksLabel.setText("Drinks");

        water.setBackground(new java.awt.Color(255, 255, 255));
        water.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 36)); // NOI18N
        water.setForeground(new java.awt.Color(0, 102, 204));
        water.setText("Water");

        waterCounter.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        waterCounter.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        waterCounter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                waterCounterStateChanged(evt);
            }
        });

        waterprice.setBackground(new java.awt.Color(255, 255, 255));
        waterprice.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 27)); // NOI18N
        waterprice.setForeground(new java.awt.Color(0, 102, 204));
        waterprice.setText("0.0 LE ");

        pepsi.setBackground(new java.awt.Color(255, 255, 255));
        pepsi.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 36)); // NOI18N
        pepsi.setForeground(new java.awt.Color(0, 102, 204));
        pepsi.setText("Pepsi");

        pepsiCounter.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        pepsiCounter.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        pepsiCounter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pepsiCounterStateChanged(evt);
            }
        });

        pepsiprice.setBackground(new java.awt.Color(255, 255, 255));
        pepsiprice.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 27)); // NOI18N
        pepsiprice.setForeground(new java.awt.Color(0, 102, 204));
        pepsiprice.setText("0.0 LE ");

        javax.swing.GroupLayout drinksPanelLayout = new javax.swing.GroupLayout(drinksPanel);
        drinksPanel.setLayout(drinksPanelLayout);
        drinksPanelLayout.setHorizontalGroup(
            drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(water)
                    .addComponent(pepsi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pepsiCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drinksPanelLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(waterprice)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drinksPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pepsiprice)
                        .addGap(147, 147, 147))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drinksPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(drinksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302))
        );
        drinksPanelLayout.setVerticalGroup(
            drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksPanelLayout.createSequentialGroup()
                .addComponent(drinksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(water, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterprice, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(drinksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pepsi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pepsiCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pepsiprice, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        price1.setBackground(new java.awt.Color(255, 255, 255));

        price.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        price.setForeground(new java.awt.Color(0, 102, 204));
        price.setText("Price");

        totalLabel.setBackground(new java.awt.Color(255, 255, 255));
        totalLabel.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 27)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(0, 102, 204));
        totalLabel.setText(" Total : 0.0 LE");

        subtotal.setBackground(new java.awt.Color(255, 255, 255));
        subtotal.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 27)); // NOI18N
        subtotal.setForeground(new java.awt.Color(0, 102, 204));
        subtotal.setText(" SubTotal : 0.0 LE");

        taxlabel.setBackground(new java.awt.Color(255, 255, 255));
        taxlabel.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 30)); // NOI18N
        taxlabel.setForeground(new java.awt.Color(0, 102, 204));
        taxlabel.setText("Tax : 0.0 LE");

        javax.swing.GroupLayout price1Layout = new javax.swing.GroupLayout(price1);
        price1.setLayout(price1Layout);
        price1Layout.setHorizontalGroup(
            price1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, price1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(price1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(price1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addGroup(price1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(taxlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(price1Layout.createSequentialGroup()
                        .addComponent(totalLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        price1Layout.setVerticalGroup(
            price1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(price1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taxlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        receiptPanel.setBackground(new java.awt.Color(255, 255, 255));

        Price2.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        Price2.setForeground(new java.awt.Color(0, 102, 204));
        Price2.setText("Price");

        newreceipt.setBackground(new java.awt.Color(255, 255, 255));
        newreceipt.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        newreceipt.setForeground(new java.awt.Color(0, 51, 153));
        newreceipt.setText("New Bill");
        newreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newreceiptActionPerformed(evt);
            }
        });

        saveReciept.setBackground(new java.awt.Color(255, 255, 255));
        saveReciept.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        saveReciept.setForeground(new java.awt.Color(0, 51, 153));
        saveReciept.setText("Save Bill");
        saveReciept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRecieptActionPerformed(evt);
            }
        });

        calculate2.setBackground(new java.awt.Color(255, 255, 255));
        calculate2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        calculate2.setForeground(new java.awt.Color(0, 51, 153));
        calculate2.setText("Calculate");
        calculate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout receiptPanelLayout = new javax.swing.GroupLayout(receiptPanel);
        receiptPanel.setLayout(receiptPanelLayout);
        receiptPanelLayout.setHorizontalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receiptPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Price2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(receiptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newreceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveReciept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calculate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        receiptPanelLayout.setVerticalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Price2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calculate2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveReciept, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(restaurantPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(drinksPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sandwichesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(receiptPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(price1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(restaurantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(receiptPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sandwichesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drinksPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chickenCounterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chickenCounterStateChanged

        // to save the checken counter pbject value in chickenNum variable and make operations on it
       chickenNum=(Integer) chickenCounter.getValue();
       chickenPrice=CHICKEN_COST*chickenNum;
      checkenSndwichPrice.setText(chickenPrice+" LE");
        
    }//GEN-LAST:event_chickenCounterStateChanged

    private void meatCounterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_meatCounterStateChanged
       
        // to save the meet counter pbject value in meetNum variable and make operations on it
       meatNum=(Integer) meatCounter.getValue();
       meatPrice=MEAT_COST*meatNum;
      meatSandwichPrice.setText(meatPrice+" LE");
        
        
    }//GEN-LAST:event_meatCounterStateChanged

    private void frenchFreisCounterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_frenchFreisCounterStateChanged

                // to save the meet counter pbject value in meetNum variable and make operations on it
       frenchFreisNum=(Integer) frenchFreisCounter.getValue();
       frenchFreisPrice=FRENCH_FREIS_COST*frenchFreisNum;
       frenchFreisSandwichPrice.setText(frenchFreisPrice+" LE");
        

    }//GEN-LAST:event_frenchFreisCounterStateChanged

    private void waterCounterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_waterCounterStateChanged
         
        // to save the water counter object value in waterNum variable and make operations on it
       waterNum=(Integer) waterCounter.getValue();
       waterPrice=WATER_COST*waterNum;
       waterprice.setText(waterPrice+" LE");
      
    }//GEN-LAST:event_waterCounterStateChanged

    private void pepsiCounterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pepsiCounterStateChanged
        
          // to save the pepsi counter pbject value in pepsiNum variable and make operations on it
       pepsiNum=(Integer) pepsiCounter.getValue();
       pepsiPrice=PEPSI_COST*pepsiNum;
       pepsiprice.setText(pepsiPrice+" LE");
        
    }//GEN-LAST:event_pepsiCounterStateChanged

    private void chickenextraCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenextraCheeseActionPerformed
        
        if(chickenextraCheese.isSelected())   chickenPrice+=5*chickenNum;
            else   chickenPrice-=5*chickenNum;
        
      checkenSndwichPrice.setText(chickenPrice+" LE");

    }//GEN-LAST:event_chickenextraCheeseActionPerformed

    private void meetExtraCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetExtraCheeseActionPerformed
     
        if(meetExtraCheese.isSelected())   meatPrice+=5*meatNum;
            else   meatPrice-=5*meatNum;
        
      meatSandwichPrice.setText(meatPrice+" LE");
    }//GEN-LAST:event_meetExtraCheeseActionPerformed

    private void freisExtraCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freisExtraCheeseActionPerformed

          if(freisExtraCheese.isSelected())   frenchFreisPrice+=5*frenchFreisNum;
            else   frenchFreisPrice-=5*frenchFreisNum;
        
      frenchFreisSandwichPrice.setText(frenchFreisPrice+" LE");

    }//GEN-LAST:event_freisExtraCheeseActionPerformed

    private void calculate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate2ActionPerformed

           subTotal= chickenPrice+meatPrice +frenchFreisPrice+waterPrice+pepsiPrice;
           subtotal.setText("SubTotal : "+subTotal+" LE");
           
           tax=subTotal*0.1;
           tax*=100;
           tax=(double)((int) tax);
           tax/=100;
           taxlabel.setText("Tax : "+tax+" LE");
           
           total=subTotal+tax;
           totalLabel.setText("Total : "+total+" LE");
           
    }//GEN-LAST:event_calculate2ActionPerformed

    private void saveRecieptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRecieptActionPerformed
        
        try {
            if(total!=0){
             output = new PrintWriter("billNumber."+billCounter+".txt");
            
            output.println("   Bill number : "+billCounter+1);
            output.println("-----------------");
            output.println(" ");

            if(chickenNum !=0){
                 output.print(chickenNum+" chicken Shawarma");
                 
                 if(chickenextraCheese.isSelected()){
                     output.println(" with extra cheese.");
                 }
            }
            
            
             if(meatNum !=0){
                 output.print(meatNum+" meat Shawarma");
                 
                 if(meetExtraCheese.isSelected()){
                     output.println(" with extra cheese.");
                 }
            }
             
              if(frenchFreisNum !=0){
                 output.print(frenchFreisNum+" french Freis ");
                 
                 if(freisExtraCheese.isSelected()){
                     output.println(" with extra cheese.");
                 }
            }
              
               if(waterNum !=0){
                 output.print(waterNum+" water ");
                 output.println(waterPrice+" LE");

            }
               
                if(pepsiNum !=0){
                 output.print(pepsiNum+" pepsi ");
                 output.println(pepsiPrice+" LE \n");

            }
                 output.println("----------------------");
                 output.println();
             output.println("sub total : "+subTotal+" LE");
            output.println("tax : "+tax+" LE");
            output.println("total :"+total+" LE");
                 output.println("----------------------");
                 output.println("thank you for your order");


             
            }output.close();
        } 
        catch (FileNotFoundException ex) {
            Logger.getLogger(restaurantManagementSytsem.class.getName()).log(Level.SEVERE, null, ex);
        }

          
    }//GEN-LAST:event_saveRecieptActionPerformed

    private void newreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newreceiptActionPerformed

      if(total !=0){
          chickenCounter.setValue(0);
          meatCounter.setValue(0);
          frenchFreisCounter.setValue(0);
          waterCounter.setValue(0);
          pepsiCounter.setValue(0);
          
          chickenextraCheese.setSelected(false);
          meetExtraCheese.setSelected(false);
          freisExtraCheese.setSelected(false);

          subtotal.setText("SubTotal : 0.0 LE");
          taxlabel.setText("Tax : 0.0 LE");
          totalLabel.setText("Total : 0.0 LE");
          
          subTotal=0;
          tax=0;
          total=0;
          billCounter++;
          billNum.setText("Bill Number : "+billCounter);
      }

    }//GEN-LAST:event_newreceiptActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new restaurantManagementSytsem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BeefShawarma;
    private javax.swing.JLabel FrenchFries;
    private javax.swing.JLabel Price2;
    private javax.swing.JLabel billNum;
    private javax.swing.JButton calculate2;
    private javax.swing.JLabel checkenSndwichPrice;
    private javax.swing.JSpinner chickenCounter;
    private javax.swing.JLabel chickenShawarma1;
    private javax.swing.JCheckBox chickenextraCheese;
    private javax.swing.JLabel drinksLabel;
    private javax.swing.JPanel drinksPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JCheckBox freisExtraCheese;
    private javax.swing.JSpinner frenchFreisCounter;
    private javax.swing.JLabel frenchFreisSandwichPrice;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JSpinner meatCounter;
    private javax.swing.JLabel meatSandwichPrice;
    private javax.swing.JCheckBox meetExtraCheese;
    private javax.swing.JButton newreceipt;
    private javax.swing.JLabel pepsi;
    private javax.swing.JSpinner pepsiCounter;
    private javax.swing.JLabel pepsiprice;
    private javax.swing.JLabel price;
    private javax.swing.JPanel price1;
    private javax.swing.JPanel receiptPanel;
    private javax.swing.JLabel restaurantLabel;
    private javax.swing.JPanel restaurantPanel;
    private javax.swing.JLabel sandwichesLabel;
    private javax.swing.JPanel sandwichesPanel;
    private javax.swing.JButton saveReciept;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel taxlabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel water;
    private javax.swing.JSpinner waterCounter;
    private javax.swing.JLabel waterprice;
    // End of variables declaration//GEN-END:variables
}
